# -*- coding: utf-8 -*-
"""Опорные объекты.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HTOKTwracaFrqItKnmMMjI1wW7-i4rmj
"""

import pandas as pd
from sklearn import svm
df_train = pd.read_csv(f'./drive/My Drive/svm-data.csv', header=None)

X = df_train[df_train.columns[1:3]]
y = df_train[df_train.columns[0]]
clf = svm.SVC(kernel='linear', C = 100000, random_state=241)
clf.fit(X,y)
f = clf.support_
f
