# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I7YuUZ9v-7YrRrXTcu0xeRyrZSyDQSJN
"""

import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier

file = pd.read_csv("titanic.csv");
file.drop(['SibSp','Parch','Ticket','Cabin','Embarked','Survived','Name','PassengerId'],axis='columns', inplace=True);
file.dropna(subset=['Age','Sex','Pclass','Fare'], inplace=True)
#file.Sex.apply(lambda i : 1 if i == "female" else 0)
file.loc[(file.Sex == 'female'), 'Sex'] = 1.0
file.loc[(file.Sex == 'male'), 'Sex'] = 0.0
array = file.values

X = array[:,0:4]

Y = array[:,3]
Y=Y.astype('int')

# feature extraction

model = DecisionTreeClassifier(random_state=241)

model.fit(X, Y)

print(model.feature_importances_)