# -*- coding: utf-8 -*-
"""Test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vTwBqHf1PVP1_s-PLtInABliJesEt_FJ
"""

import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import KFold
from sklearn.model_selection import *
from sklearn.preprocessing import *
from sklearn import metrics
X = pd.read_csv(f'./drive/My Drive/wine.data', header=None, usecols=list(range(1,14)))
Y = pd.read_csv(f'./drive/My Drive/wine.data', header=None, usecols=[0]).values.reshape(len(X),)
kf = KFold(n_splits=5, shuffle=True, random_state=42)
kMeans = list()
for k in range(1, 51):
    kn = KNeighborsClassifier(n_neighbors=k)
    kn.fit(X, Y);
    array = cross_val_score(estimator=kn, X=X, y=Y, cv=kf, scoring='accuracy')
    m = array.mean()
    kMeans.append(m)   
 
m = max(kMeans)
indices = [i for i, j in enumerate(kMeans) if j == m]
 
print(indices[0]+1)
print(np.round(m,decimals=2))
 
X_scale = scale(X)
 
kMeans = list()
for k in range(1, 51):
    kn = KNeighborsClassifier(n_neighbors=k)
    array = cross_val_score(estimator=kn, X=X_scale, y=Y, cv=kf, scoring='accuracy')
    m = array.mean()
    kMeans.append(m)   
 
m = max(kMeans)
indices = [i for i, j in enumerate(kMeans) if j == m]
 
print(indices[0]+1)
print(np.round(m,decimals=2))
print()