# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I7YuUZ9v-7YrRrXTcu0xeRyrZSyDQSJN
"""

import pandas as pd
import numpy as np

file = pd.read_csv("titanic.csv");

print('Количество измерений:\n',file.groupby('Sex').count()[['Name']],'\n\n')
print('Количество выживших\умерших:\n',file.groupby('Survived').count()[['Name']],'\n\n')
print((file['Survived'].value_counts()/file['Survived'].count())*100,'\n\n')
print((file['Pclass'].value_counts()/file['Pclass'].count())*100,'\n\n')
print('Среднее арифметическое:\n',file.Age.mean(),'\n\n')
print('Медиана:\n',file.Age.median(),'\n\n')
print('Коэффициент корреляции Пирсона:\n',file["SibSp"].corr( file["Parch"]),'\n\n')
