# -*- coding: utf-8 -*-
"""Test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vTwBqHf1PVP1_s-PLtInABliJesEt_FJ
"""

import numpy as np
import pandas as pd
from sklearn.linear_model import Perceptron
import sklearn.metrics
from sklearn.preprocessing import StandardScaler
X_train = pd.read_csv(f'./drive/My Drive/perceptron_train.csv', header=None, usecols=list(range(1,3)))
y_train = pd.read_csv(f'./drive/My Drive/perceptron_train.csv', header=None, usecols=list(range(0,1)))
X_test = pd.read_csv(f'./drive/My Drive/perceptron_test.csv', header=None, usecols=list(range(1,3)))
y_test = pd.read_csv(f'./drive/My Drive/perceptron_test.csv', header=None, usecols=list(range(0,1)))
clf = Perceptron(random_state=241)
clf.fit(X_train, y_train)
predictions = clf.predict(X_train)
s_1 = sklearn.metrics.accuracy_score(y_train,predictions)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
clf.fit(X_train_scaled, y_train.values.ravel())

predictions = clf.predict(X_test_scaled)
s2 = sklearn.metrics.accuracy_score(y_test.values.ravel(), predictions) 
print(s2 - s_1)
